import { CURRENT_SCHEMA_VERSION, PersistentGalleryData } from '@/lib/persistence/schema';
import { objectStorage } from '@/lib/persistence/storage';

const seededStorageKeys = [
  'placeholder-1.jpg',
  'placeholder-2.jpg',
  'placeholder-3.jpg',
  'placeholder-4.jpg',
  'placeholder-5.jpg',
  'placeholder-6.jpg',
  'placeholder-7.jpg',
  'placeholder-8.jpg',
  'placeholder-9.jpg',
];

export const seededData: PersistentGalleryData = {
  schemaVersion: CURRENT_SCHEMA_VERSION,
  photos: [
    {
      id: '1',
      title: 'Sunset Landscape',
      tags: ['landscape', 'sunset', 'nature'],
      likes: 124,
      downloads: 45,
      views: 1205,
      photographer: 'John Doe',
      dateTaken: '2024-01-15',
      storageKey: seededStorageKeys[0],
      metadataKey: objectStorage.resolveMetadataKey(seededStorageKeys[0]),
    },
    {
      id: '2',
      title: 'Portrait Study',
      tags: ['portrait', 'studio', 'professional'],
      likes: 89,
      downloads: 23,
      views: 892,
      photographer: 'Jane Smith',
      dateTaken: '2024-01-10',
      storageKey: seededStorageKeys[1],
      metadataKey: objectStorage.resolveMetadataKey(seededStorageKeys[1]),
    },
    {
      id: '3',
      title: 'Architecture',
      tags: ['architecture', 'building', 'city'],
      likes: 156,
      downloads: 67,
      views: 1543,
      photographer: 'Mike Johnson',
      dateTaken: '2024-01-08',
      storageKey: seededStorageKeys[2],
      metadataKey: objectStorage.resolveMetadataKey(seededStorageKeys[2]),
    },
    {
      id: '4',
      title: 'Nature Close-up',
      tags: ['macro', 'nature', 'flowers'],
      likes: 203,
      downloads: 89,
      views: 2134,
      photographer: 'Sarah Wilson',
      dateTaken: '2024-01-05',
      storageKey: seededStorageKeys[3],
      metadataKey: objectStorage.resolveMetadataKey(seededStorageKeys[3]),
    },
    {
      id: '5',
      title: 'Street Photography',
      tags: ['street', 'candid', 'urban'],
      likes: 91,
      downloads: 34,
      views: 765,
      photographer: 'Alex Brown',
      dateTaken: '2024-01-03',
      storageKey: seededStorageKeys[4],
      metadataKey: objectStorage.resolveMetadataKey(seededStorageKeys[4]),
    },
    {
      id: '6',
      title: 'Wedding Moment',
      tags: ['wedding', 'love', 'ceremony'],
      likes: 267,
      downloads: 112,
      views: 3421,
      photographer: 'Emma Davis',
      dateTaken: '2024-01-01',
      storageKey: seededStorageKeys[5],
      metadataKey: objectStorage.resolveMetadataKey(seededStorageKeys[5]),
    },
    {
      id: '7',
      title: 'Mountain Vista',
      tags: ['landscape', 'mountain', 'adventure'],
      likes: 189,
      downloads: 78,
      views: 1876,
      photographer: 'David Chen',
      dateTaken: '2023-12-28',
      storageKey: seededStorageKeys[6],
      metadataKey: objectStorage.resolveMetadataKey(seededStorageKeys[6]),
    },
    {
      id: '8',
      title: 'Urban Nightscape',
      tags: ['night', 'city', 'lights'],
      likes: 234,
      downloads: 95,
      views: 2543,
      photographer: 'Lisa Martinez',
      dateTaken: '2023-12-25',
      storageKey: seededStorageKeys[7],
      metadataKey: objectStorage.resolveMetadataKey(seededStorageKeys[7]),
    },
    {
      id: '9',
      title: 'Wildlife Portrait',
      tags: ['wildlife', 'nature', 'animal'],
      likes: 312,
      downloads: 143,
      views: 4321,
      photographer: 'Tom Anderson',
      dateTaken: '2023-12-20',
      storageKey: seededStorageKeys[8],
      metadataKey: objectStorage.resolveMetadataKey(seededStorageKeys[8]),
    },
  ],
  galleries: [
    {
      id: '1',
      name: 'Wedding - Sarah & John',
      type: 'Client Review',
      photoIds: ['6', '2', '1'],
      views: 234,
      status: 'Active',
      lastUpdatedAt: '2026-08-11T10:00:00.000Z',
    },
    {
      id: '2',
      name: 'Corporate Headshots',
      type: 'Public',
      photoIds: ['2', '5'],
      views: 1234,
      status: 'Published',
      lastUpdatedAt: '2026-08-10T10:00:00.000Z',
    },
    {
      id: '3',
      name: 'Nature Portfolio',
      type: 'Portfolio',
      photoIds: ['1', '4', '7', '9'],
      views: 5678,
      status: 'Published',
      lastUpdatedAt: '2026-08-08T10:00:00.000Z',
    },
    {
      id: '4',
      name: 'Street Photography',
      type: 'Draft',
      photoIds: ['5', '8'],
      views: 0,
      status: 'Draft',
      lastUpdatedAt: '2026-08-04T10:00:00.000Z',
    },
  ],
  users: [
    {
      id: 'u1',
      name: 'Admin User',
      role: 'admin',
      createdAt: '2026-01-01T00:00:00.000Z',
    },
  ],
};
